### ISSUE TITLE
Layout.ejb not found for view in a subfolder

### ISSUE THREAD

**Issue by gerardo-navarro** [jaxcore/sails-react-redux-boilerplate#3]
Hi Dan,

I want to organize my views in subfolders, e.g.`views/misc/sailshomepage.ejs`. Unfortunately, it is not working because the layout.ejs is not found. Do you have an idea about the underlying problem?

Checkout the fork (https://github.com/gerardo-navarro/sails-react-redux-boilerplate/tree/layout_not_found) to repoduce the error. I only copied the existing `views/sailshomepage.ejs` to `views/misc/sailshomepage.ejs` and adjusted the `config/routes.js`.

When starting `npm run dev` and visiting `http://localhost:1337/sailshomepage` you get
```
{"stack":"Error: ENOENT: no such file or directory, open '/Users/gerardonavarrosuarez/Development/edeka-prototyping/sails-react-redux-boilerplate/layout.ejs'
at Error (native)
at Object.fs.openSync (fs.js:640:18)
at fs.readFileSync (fs.js:508:33)
at Object.exports.renderFile (/Users/gerardonavarrosuarez/Development/edeka-prototyping/sails-react-redux-boilerplate/node_modules/ejs-locals/node_modules/ejs/lib/ejs.js:313:9)
at module.exports (/Users/gerardonavarrosuarez/Development/edeka-prototyping/sails-react-redux-boilerplate/node_modules/ejs-locals/index.js:85:7)
at /Users/gerardonavarrosuarez/Development/edeka-prototyping/sails-react-redux-boilerplate/node_modules/ejs-locals/index.js:131:7
at Object.exports.renderFile (/Users/gerardonavarrosuarez/Development/edeka-prototyping/sails-react-redux-boilerplate/node_modules/ejs-locals/node_modules/ejs/lib/ejs.js:318:3)
at SailsView.module.exports [as engine] (/Users/gerardonavarrosuarez/Development/edeka-prototyping/sails-react-redux-boilerplate/node_modules/ejs-locals/index.js:85:7)
at ...
```

Any thoughts?

**Comment by dsteinman** [comment]
I actually haven't used ejs layouts before making this boilerplate.  But if you look at /config/views.js the authors of Sails have some information about "local" layouts in your Controller.  If that doesn't work you could disable the layouts entirely and just do includes, you'd just have to copy the contents of the layout into header/footer templates.

**Comment by dsteinman** [comment]
I was mistaken, the sails layout config wasn't working and so I added my own code to /config/http.js

To disable it you can remark out this line:

app.use(expressLayouts);

**Comment by gerardo-navarro** [comment]
@dsteinman Do you remember why you had to use expressLayouts there and why you cannot simply rely on the normal layout functionality provided by sails?

**Comment by dsteinman** [comment]
No, I didn't find out why the sails ejs layouts weren't working for me.

You should be able to return to sails default settings by remarking out this line in `config/http.js`

``` // app.use(expressLayouts);```

And then enabling the default layout system in `config/views.js` 

```layout: 'layout',```

It was due to these and other config issues especially revolving around sessions/redis and a bunch of other goals I had, that I ended up deciding not to use Sails and began work on a new framework of my own.
